version: "3"

networks:
  web:
    driver: bridge

services:
  db:
    image: mysql:5.7
    restart: always
    networks:
      - web
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kritik
    volumes:
      - /Users/pierre/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    networks:
      - web
    ports:
      - 8080:8080